# LiveKit Egress Configuration - Production Ready
# Handles recording and streaming output

# Redis configuration - Using existing instance
redis:
  address: redis:6379
  username: ""
  password: ${REDIS_PASSWORD:-}
  db: 0
  use_tls: false

# API credentials (must match LiveKit server)
api_key: ${LIVEKIT_API_KEY:-APIcQP8xHwvsq7d}
api_secret: ${LIVEKIT_API_SECRET:-RJ3CeZtWyb6d3cQPDfLfDxOjVmzxJKh6pb0i3bIyeI3B}

# WebSocket URL for LiveKit server connection
ws_url: wss://lk.delo.sh

# Health check configuration
health_port: 9090

# Logging configuration
logging:
  json: false
  level: info

# Development mode
development: false

# Template configuration for recordings
template_base: /templates

# Output storage configuration
storage:
  # Local storage for recordings
  local_directory: /recordings
  # File naming pattern
  filename_prefix: "livekit-recording"
  # File format suffix
  filename_suffix: ""

# CPU and resource limits for egress processing  
cpu_cost:
  # Cost per room composite recording
  room_composite_cpu_cost: 4.0
  # Cost per track composite recording
  track_composite_cpu_cost: 2.0
  # Cost per track recording
  track_cpu_cost: 1.0
  # Cost per stream output
  stream_cpu_cost: 2.0
  # Maximum concurrent recordings
  max_cpu_utilization: 0.9

# Audio recording configuration
audio:
  # Default audio recording settings
  bitrate: 128000
  channels: 2
  sample_rate: 48000
  # Audio codec for recordings
  codec: opus

# Video recording configuration
video:
  # Default video recording settings
  width: 1920
  height: 1080
  framerate: 30
  bitrate: 4000000
  # Video codec for recordings
  codec: h264
  # Hardware acceleration
  hardware_encoder: auto
  # Video profile
  profile: main

# Room composite recording configuration
room_composite:
  # Default layout for room recordings
  layout: grid
  # Custom CSS for styling (optional)
  custom_css: ""
  # Enable audio-only recordings
  audio_only: false
  # Video resolution for composites
  width: 1920
  height: 1080

# Stream output configuration
stream:
  # Default stream settings
  # Add your streaming endpoints here
  rtmp_outputs: []
  # Example:
  # rtmp_outputs:
  #   - urls: ["rtmp://stream.example.com/live/stream_key"]

# File output configuration
file:
  # Default file output settings
  disable_manifest: false
  # Segment configuration for HLS/DASH
  segments_info:
    playlist_name: "index.m3u8"
    segment_duration: 6

# Webhook configuration for egress events
webhook:
  # URLs to receive egress event notifications
  # urls: ["https://your-app.com/webhook/egress"]

# Advanced processing options
processing:
  # Enable GPU acceleration if available
  gpu_acceleration: auto
  # Number of processing threads
  worker_threads: 0  # 0 = auto-detect
  # Memory limit for processing
  memory_limit: "4GB"

# Cleanup configuration
cleanup:
  # Cleanup temporary files after processing
  cleanup_temp_files: true
  # Retention period for completed recordings
  retention_days: 30