# LiveKit Ingress Configuration - Production Ready
# Handles RTMP/WHIP/WebRTC input streams

# Redis configuration - Using existing instance
redis:
  address: redis:6379
  username: ""
  password: ${REDIS_PASSWORD:-}
  db: 0
  use_tls: false

# API credentials (must match LiveKit server)
api_key: ${LIVEKIT_API_KEY:-APIcQP8xHwvsq7d}
api_secret: ${LIVEKIT_API_SECRET:-RJ3CeZtWyb6d3cQPDfLfDxOjVmzxJKh6pb0i3bIyeI3B}

# WebSocket URL for LiveKit server connection
ws_url: wss://lk.delo.sh

# RTMP configuration
rtmp_port: 1935

# WHIP configuration (WebRTC-HTTP Ingestion Protocol)
whip_port: 8080

# HTTP relay port for ingress management
http_relay_port: 9090

# Logging configuration
logging:
  json: false
  level: info

# Development mode
development: false

# RTC configuration for ingress streams
rtc_config:
  udp_port: 7885
  use_external_ip: true
  enable_loopback_candidate: false
  # ICE candidate generation timeout
  ice_candidate_timeout: 10s

# CPU and resource limits for ingress processing
cpu_cost:
  # Cost per RTMP stream
  rtmp_cpu_cost: 3.0
  # Cost per WHIP stream  
  whip_cpu_cost: 2.0
  # Maximum concurrent streams
  max_cpu_utilization: 0.8

# Storage configuration for temporary files
storage:
  # Temporary storage for stream processing
  temp_path: /tmp/ingress
  # Cleanup interval for temp files
  cleanup_interval: 30m

# Audio processing configuration
audio:
  # Default audio settings for ingested streams
  bitrate: 64000
  channels: 2
  sample_rate: 48000

# Video processing configuration
video:
  # Default video settings for ingested streams
  width: 1920
  height: 1080
  framerate: 30
  bitrate: 3000000
  # Hardware acceleration
  hardware_encoder: auto

# Stream validation
validation:
  # Validate stream format before processing
  check_format: true
  # Maximum stream duration (0 = unlimited)
  max_duration: 0
  # Require authentication for streams
  require_auth: false