# LiveKit Server Configuration - SSL OPTIMIZED & CORRECTED
# All external URLs use HTTPS with proper certificates

# Server binding configuration
port: 7880
bind_addresses:
  - ""

# Redis configuration - Using existing instance if available
redis:
  address: redis:6379
  username: ""
  password: ""
  db: 0

# WebRTC configuration optimized for SSL
rtc:
  tcp_port: 7881
  port_range_start: 61000
  port_range_end: 61050
  use_external_ip: true

# TURN server configuration with SSL
turn:
  enabled: true
  domain: lk-turn.delo.sh
  tls_port: 5349
  udp_port: 3478
  external_tls: true

# API Keys
keys:
  APIcQP8xHwvsq7d: RJ3CeZtWyb6d3cQPDfLfDxOjVmzxJKh6pb0i3bIyeI3B

# Ingress configuration with HTTPS URLs
ingress:
  rtmp_base_url: rtmp://lk.delo.sh:1935/x
  whip_base_url: https://lk-whip.delo.sh/w

# Logging configuration
log_level: info
development: false